# Generated by Django 3.1.3 on 2021-08-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=20, unique=True, verbose_name='아이디')),
                ('user_pw', models.CharField(max_length=50, verbose_name='비밀번호')),
                ('user_register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='계정 생성시간')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
