# Generated by Django 3.1.3 on 2021-08-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userID',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='아이디'),
            preserve_default=False,
        ),
    ]
